### ISSUE TITLE
Bug: Not installed in Apps

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/ProjectBoard#58] opened 2022-06-21 13:15 UTC
As a user, I read in the readme that "Download the latest .sar from the [releases section](https://github.com/hpi-swa-teaching/ProjectBoard/releases), drag it onto your open squeak-image and press install sar. The shortcut from the apps menu will be installed automagically." However, there was no Squello option installed in the apps menu. The method #registerInAppsMenu also has no senders.
I would expect that either the baseline or the Board class initialization would add the shortcut.

**Comment by SaturnHafen** [comment] 2022-07-14 16:18
Hi and thanks for the report!
The Shortcut is created inside the preamble of the `.sar` ([preamble](https://github.com/hpi-swa-teaching/ProjectBoard/blob/master/Squello-Tests.package/SPBSarFileGenerator.class/instance/generatePreamble..st#L6)) which is why it has no senders as far as squeak is concerned.

We tried to reproduce your issue using a Squeak 5.2 Image/VM from [squeak.org](https://files.squeak.org/5.2/Squeak5.2-18234-64bit/) (and a current SWT-22 Squeak Image/VM from [the moodle](https://moodle.hpi.de)) but in both cases, squello installed without any issue.
Could you please elaborate on how you installed the sar?

**Comment by SaturnHafen** [comment] 2022-08-03 17:15
I am going to close this issue because we are unable to reproduce the problem. Feel free to re-open if the problem occurs again!

**Closed by SaturnHafen** 2022-08-03 17:15 UTC
Labels: bug, User Story
